# Site settings
title: 쿡쿡하세요~쿡쿡
description: > # this means to ignore newlines until "baseurl:"
  I am migrating from a blog service provider to github, still trying out with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leeayoung.github.io" # the base hostname & protocol for your site
twitter_username: jissuetissue
github_username:  leeayoung

# Build settings
markdown: kramdown

# Time zone
timezone: Asia/Korea
